export const formInitialValues = {
    userId:'',
    name:'',
    lastName:'',
    phone:'',
    city:'',
    country:'',
    gender:'',
    employmentStatus:'',
    idealJob:'', 
    educationLevelId:3,
    urlCv: '',
    urlLinkedin: '',
    urlGithub: '',
    urlPortfolio: '',
    details: '',
    yearsExperience: 0, 
    studies:[ ],  
    positions: [ ],
    languages:[ ],
    frameworks:[],
    tools:[],
    jobs:[],
    softSkills: [ ],    
    visas: [],
    englishLevel:[],
    currentSituation:[],
    betterSituation: []
}

