export const formInitialValues = {
    nameInfo:'',
    lastName:'',
    email:'',
    phone:'',
    city:'',
    country:'',
    gender:'',
    employmentStatus:'',
    idealJob: [
    ],
    educationLevelId:'',
    newTec:'',
    englishLevel:'',
    studies:[],
    actual:'',
    more:'',
    urlCv: '',
    urlLinkedin: '',
    urlGithub: '',
    urlPortafolio: '',
    details: '',
    softSkills: [],
    yearsExperience: '',
    availableOptions: '',
    descriptionIdealJob: '',
    workOption: '',
    visas: [],
}