//version anterior commit a1a32d2
export const testData = [
  {
    testId: 1,
    testCategory: "languages",
    testName: "HTML",
    testTime: 10,
    role: "Desarrollador/a Front End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=HTML",
    testLogo:
      "https://www.freepnglogos.com/uploads/html5-logo-png/html5-logo-html-logo-0.png",
  },
  {
    testId: 2,
    testCategory: "languages",
    testName: "CSS",
    testTime: 20,
    role: "Desarrollador/a Front End",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=CSS",
    testLogo:
      "https://seeklogo.com/images/C/css-3-logo-023C1A7171-seeklogo.com.png",
  },
  {
    testId: 3,
    testCategory: "languages",
    testName: "JavaScript",
    testTime: 30,
    role: "Desarrollador/a Full Stack",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=JS",
    testLogo:
      "https://thumbs.dreamstime.com/b/javascript-logo-javascript-logo-white-background-vector-format-available-136765881.jpg",
  },
  {
    testId: 4,
    testCategory: "frameworks",
    testName: "SQL",
    testTime: 40,
    role: "Desarrollador/a Full Stack",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=SQL",
    testLogo:
      "https://thumbs.dreamstime.com/b/sql-database-icon-logo-design-ui-ux-app-orange-inscription-shadow-96841969.jpg",
  },
  {
    testId: 5,
    testCategory: "frameworks",
    testName: "MySQL",
    testTime: 10,
    role: "Desarrollador/a Full Stack",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=MySQL",
    testLogo: "https://1000logos.net/wp-content/uploads/2020/08/MySQL-Logo.png",
  },
  {
    testId: 6,
    testCategory: "languages",
    testName: "Python",
    testTime: 20,
    role: "Desarrollador/a Full Stack",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=PYTHON",
    testLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1869px-Python-logo-notext.svg.png",
  },
  {
    testId: 7,
    testCategory: "languages",
    testName: "PHP",
    testTime: 30,
    role: "Desarrollador Back End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=PHP",
    testLogo:
      "https://cdn.freebiesupply.com/logos/large/2x/php-1-logo-svg-vector.svg",
  },
  {
    testId: 8,
    testCategory: "frameworks",
    testName: "Jquery",
    testTime: 40,
    role: "Desarrollador Back End",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=JQUERY",
    testLogo:
      "https://seeklogo.com/images/J/jquery-logo-CFE6ECE363-seeklogo.com.png",
  },
  {
    testId: 9,
    testCategory: "frameworks",
    testName: "Bootstrap",
    testTime: 10,
    role: "Desarrollador/a Front End",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=BOOTSTRAP",
    testLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/512px-Bootstrap_logo.svg.png",
  },
  {
    testId: 10,
    testCategory: "frameworks",
    testName: "React",
    testTime: 20,
    role: "Desarrollador/a Front End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=REACT",
    testLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
  },
  {
    testId: 11,
    testCategory: "languages",
    testName: "Java",
    testTime: 30,
    role: "Desarrollador Back End",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=JAVA",
    testLogo: "https://cdn-icons-png.flaticon.com/512/226/226777.png",
  },
  {
    testId: 12,
    testCategory: "languages",
    testName: "C",
    testTime: 40,
    role: "Desarrollador Back End",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.php?qtest=C",
    testLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/C_Programming_Language.svg/695px-C_Programming_Language.svg.png",
  },
  {
    testId: 13,
    testCategory: "languages",
    testName: "C++",
    testTime: 10,
    role: "Desarrollador Back End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=CPP",
    testLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1200px-ISO_C%2B%2B_Logo.svg.png",
  },
  {
    testId: 14,
    testCategory: "languages",
    testName: "C#",
    testTime: 20,
    role: "Desarrollador Back End",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=CS",
    testLogo:
      "https://cis.msjc.edu/Tutorials/Programming/Languages/Csharp/images/Csharp_logo.png",
  },
  {
    testId: 15,
    testCategory: "languages",
    testName: "R",
    testTime: 30,
    role: "Desarrollador Back End",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=R",
    testLogo:
      "https://air-marketing-assets.imgix.net/blog/logo-db/r-logo/r-logo-svg-4.svg",
  },
  {
    testId: 16,
    testCategory: "languages",
    testName: "Kotlin",
    testTime: 40,
    role: "Desarrollador/a Front End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.php?qtest=KOTLIN",
    testLogo:
      "https://download.logo.wine/logo/Kotlin_(programming_language)/Kotlin_(programming_language)-Logo.wine.png",
  },
  {
    testId: 17,
    testCategory: "tools",
    testName: "Git",
    testTime: 10,
    role: "Desarrollador/a Full Stack",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=GIT",
    testLogo: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
  },
  {
    testId: 18,
    testCategory: "languages",
    testName: "TypeScript",
    testTime: 20,
    role: "Desarrollador/a Full Stack",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.php?qtest=TS",
    testLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/1200px-Typescript_logo_2020.svg.png",
  },
  {
    testId: 19,
    testCategory: "tools",
    testName: "AWS",
    testTime: 30,
    role: "Desarrollador Back End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.php?qtest=AWSCE",
    testLogo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png",
  },
];
