export const testData = [
  {
    id: 1,
    category: "languages",
    name: "HTML",
    time: 10,
    role: "Desarrollador/a Front End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=HTML",
    logo: "https://www.freepnglogos.com/uploads/html5-logo-png/html5-logo-html-logo-0.png",
  },
  {
    id: 2,
    category: "languages",
    name: "CSS",
    time: 20,
    role: "Desarrollador/a Front End",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=CSS",
    logo: "https://seeklogo.com/images/C/css-3-logo-023C1A7171-seeklogo.com.png",
  },
  {
    id: 3,
    category: "languages",
    name: "JavaScript",
    time: 30,
    role: "Desarrollador/a Full Stack",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=JS",
    logo: "https://thumbs.dreamstime.com/b/javascript-logo-javascript-logo-white-background-vector-format-available-136765881.jpg",
  },
  {
    id: 4,
    category: "frameworks",
    name: "SQL",
    time: 40,
    role: "Desarrollador/a Full Stack",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=SQL",
    logo: "https://thumbs.dreamstime.com/b/sql-database-icon-logo-design-ui-ux-app-orange-inscription-shadow-96841969.jpg",
  },
  {
    id: 5,
    category: "frameworks",
    name: "MySQL",
    time: 10,
    role: "Desarrollador/a Full Stack",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=MySQL",
    logo: "https://1000logos.net/wp-content/uploads/2020/08/MySQL-Logo.png",
  },
  {
    id: 6,
    category: "languages",
    name: "Python",
    time: 20,
    role: "Desarrollador/a Full Stack",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=PYTHON",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1869px-Python-logo-notext.svg.png",
  },
  {
    id: 7,
    category: "languages",
    name: "PHP",
    time: 30,
    role: "Desarrollador/a Back End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=PHP",
    logo: "https://cdn.freebiesupply.com/logos/large/2x/php-1-logo-svg-vector.svg",
  },
  {
    id: 8,
    category: "frameworks",
    name: "Jquery",
    time: 40,
    role: "Desarrollador/a Back End",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=JQUERY",
    logo: "https://seeklogo.com/images/J/jquery-logo-CFE6ECE363-seeklogo.com.png",
  },
  {
    id: 9,
    category: "frameworks",
    name: "Bootstrap",
    time: 10,
    role: "Desarrollador/a Front End",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=BOOTSTRAP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/512px-Bootstrap_logo.svg.png",
  },
  {
    id: 10,
    category: "frameworks",
    name: "React",
    time: 20,
    role: "Desarrollador/a Front End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=REACT",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
  },
  {
    id: 11,
    category: "languages",
    name: "Java",
    time: 30,
    role: "Desarrollador/a Back End",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=JAVA",
    logo: "https://cdn-icons-png.flaticon.com/512/226/226777.png",
  },
  {
    id: 12,
    category: "languages",
    name: "C",
    time: 40,
    role: "Desarrollador/a Back End",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.php?qtest=C",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/C_Programming_Language.svg/695px-C_Programming_Language.svg.png",
  },
  {
    id: 13,
    category: "languages",
    name: "C++",
    time: 10,
    role: "Desarrollador/a Back End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=CPP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1200px-ISO_C%2B%2B_Logo.svg.png",
  },
  {
    id: 14,
    category: "languages",
    name: "C#",
    time: 20,
    role: "Desarrollador/a Back End",
    difficulty: "medio",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=CS",
    logo: "https://cis.msjc.edu/Tutorials/Programming/Languages/Csharp/images/Csharp_logo.png",
  },
  {
    id: 15,
    category: "languages",
    name: "R",
    time: 30,
    role: "Desarrollador/a Back End",
    difficulty: "difícil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=R",
    logo: "https://air-marketing-assets.imgix.net/blog/logo-db/r-logo/r-logo-svg-4.svg",
  },
  {
    id: 16,
    category: "languages",
    name: "Kotlin",
    time: 40,
    role: "Desarrollador/a Front End",
    difficulty: "fácil",
    testLink: "https://www.w3schools.com/quiztest/quiztest.php?qtest=KOTLIN",
    logo: "https://download.logo.wine/logo/Kotlin_(programming_language)/Kotlin_(programming_language)-Logo.wine.png",
  },
  //   {
  //     id: 17,
  //     category: "tools",
  //     name: "Git",
  //     time: 10,
  //     role: "Desarrollador/a Full Stack",
  //     difficulty: "medio",
  //     testLink: "https://www.w3schools.com/quiztest/quiztest.asp?qtest=GIT",
  //     logo: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
  //   },
  //   {
  //     id: 18,
  //     category: "languages",
  //     name: "TypeScript",
  //     time: 20,
  //     role: "Desarrollador/a Full Stack",
  //     difficulty: "difícil",
  //     testLink: "https://www.w3schools.com/quiztest/quiztest.php?qtest=TS",
  //     logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/1200px-Typescript_logo_2020.svg.png",
  //   },
  //   {
  //     id: 19,
  //     category: "tools",
  //     name: "AWS",
  //     time: 30,
  //     role: "Desarrollador/a Back End",
  //     difficulty: "fácil",
  //     testLink: "https://www.w3schools.com/quiztest/quiztest.php?qtest=AWSCE",
  //     logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png",
  //   },
];
